[package]
name = "strictly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "strictly"

[lib]
name = "strictly_lib"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.6.0"
