name: CI

on:
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: ubuntu-latest
          EXE: strictly
          TARGET: strictly-linux-x64
          PLATFORM: linux-x64
        - os: macos-latest
          EXE: strictly
          TARGET: strictly-macos-x64
          PLATFORM: macos-x64
        # - os: windows-latest
        #   EXE: strictly.exe
        #   TARGET: strictly-windows-x64
        #   PLATFORM: windows-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: haskell/actions/setup@v1

      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Build
        run: |
          cabal install exe:strictly --install-method=copy --overwrite-policy=always --installdir=dist 
          mv dist/${{matrix.EXE}} dist/${{matrix.TARGET}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.PLATFORM}}
          path: ./${{matrix.TARGET}}
  release:
    name: release build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          path: dist
      
      - name: Install Dependencies
        run: yarn install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release