name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: haskell/actions/setup@v1

      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn run test
